### ISSUE TITLE
Gitlab integration throws error

### ISSUE THREAD

**Issue by zamirTo1** [SpectralOps/spectral-terraform-lambda-integration#1]
Hey @ChengaDev - deployed with the latest release, got this error (us-west-2).

I've also deployed the cloudformation in us-east-1 and the code and the lambda resource are different. (might worth to compare between the 2 integrations) - the Terraform deployment lambda's is missing application.

```
{
"errorType": "Runtime.UnhandledPromiseRejection",
"errorMessage": "Error: TAR_BAD_ARCHIVE: Unrecognized archive format",
"reason": {
"errorType": "Error",
"errorMessage": "TAR_BAD_ARCHIVE: Unrecognized archive format",
"code": "TAR_BAD_ARCHIVE",
"recoverable": false,
"file": "/tmp/spectral_binary.tar.gz",
"cwd": "/tmp/spectral",
"tarCode": "TAR_BAD_ARCHIVE",
"stack": [
"Error: TAR_BAD_ARCHIVE: Unrecognized archive format",
" at UnpackSync.warn (/var/task/webpack:/Users/chengazit/git/spectral-hub/packages/spectral-gitlab-webhook-scanner/node_modules/spectral-hub-shared/node_modules/tar/lib/warn-mixin.js:19:1)",
" at UnpackSync.warn (/var/task/webpack:/Users/chengazit/git/spectral-hub/packages/spectral-gitlab-webhook-scanner/node_modules/spectral-hub-shared/node_modules/tar/lib/unpack.js:220:1)",
" at UnpackSync.<anonymous> (/var/task/webpack:/Users/chengazit/git/spectral-hub/packages/spectral-gitlab-webhook-scanner/node_modules/spectral-hub-shared/node_modules/tar/lib/parse.js:81:1)",
" at UnpackSync.emit (events.js:412:35)",
" at UnpackSync.[emit] (/var/task/webpack:/Users/chengazit/git/spectral-hub/packages/spectral-gitlab-webhook-scanner/node_modules/spectral-hub-shared/node_modules/tar/lib/parse.js:285:1)",
" at UnpackSync.[maybeEnd] (/var/task/webpack:/Users/chengazit/git/spectral-hub/packages/spectral-gitlab-webhook-scanner/node_modules/spectral-hub-shared/node_modules/tar/lib/parse.js:401:1)",
" at UnpackSync.[consumeChunk] (/var/task/webpack:/Users/chengazit/git/spectral-hub/packages/spectral-gitlab-webhook-scanner/node_modules/spectral-hub-shared/node_modules/tar/lib/parse.js:432:1)",
" at UnpackSync.write (/var/task/webpack:/Users/chengazit/git/spectral-hub/packages/spectral-gitlab-webhook-scanner/node_modules/spectral-hub-shared/node_modules/tar/lib/parse.js:364:1)",
" at UnpackSync.end (/var/task/webpack:/Users/chengazit/git/spectral-hub/packages/spectral-gitlab-webhook-scanner/node_modules/spectral-hub-shared/node_modules/tar/lib/parse.js:477:1)",
" at Pipe.end (/var/task/webpack:/Users/chengazit/git/spectral-hub/packages/spectral-gitlab-webhook-scanner/node_modules/spectral-hub-shared/node_modules/minipass/index.js:75:1)"
]
},
"promise": {},
"stack": [
"Runtime.UnhandledPromiseRejection: Error: TAR_BAD_ARCHIVE: Unrecognized archive format",
" at process.<anonymous> (/var/runtime/index.js:35:15)",
" at process.emit (events.js:400:28)",
" at process.emit (/var/task/webpack:/Users/chengazit/git/spectral-hub/packages/spectral-gitlab-webhook-scanner/node_modules/source-map-support/source-map-support.js:516:1)",
" at processPromiseRejections (internal/process/promises.js:245:33)",
" at processTicksAndRejections (internal/process/task_queues.js:96:32)"
]
}
```

**Comment by ChengaDev** [comment]
Hey @zamirTo1 , thanks for reporting! :)
I just deployed the Gitlab integration via Terraform to eu-central-1 and had a successful scan.

One of our recent changes is accessing the scanner through a direct download of the binary instead of accessing it through an AWS lambda layer.
So according to the error message you attached, it seems to me that the Spectral scanner download wasn't successful for some reason and that cause the run to fail since the binary hasn't been found.
Can you see if this issue still reproduces for you?

Regarding your second point, I have checked for code differences between Gitlab Terraform & CloudFormation integrations and it seems identical.

**Comment by zamirTo1** [comment]
Hey @ChengaDev, thanks for the quick response. The error still exists.


```
START RequestId: 9e3b398d-1afa-4f5d-8820-65a638537b2d Version: $LATEST
--
END RequestId: 9e3b398d-1afa-4f5d-8820-65a638537b2d
REPORT RequestId: 9e3b398d-1afa-4f5d-8820-65a638537b2d	Duration: 4.28 ms	Billed Duration: 5 ms	Memory Size: 1024 MB	Max Memory Used: 71 MB	Init Duration: 253.82 ms
START RequestId: b4d8760e-6997-4f55-947a-72eca668528d Version: $LATEST
2022-11-16T10:58:33.526Z	b4d8760e-6997-4f55-947a-72eca668528d	INFO	START downloading spectral
2022-11-16T10:58:33.597Z	b4d8760e-6997-4f55-947a-72eca668528d	INFO	FINISH downloading spectral
2022-11-16T10:58:33.854Z	b4d8760e-6997-4f55-947a-72eca668528d	ERROR	Unhandled Promise Rejection 	{     "errorType": "Runtime.UnhandledPromiseRejection",     "errorMessage": "Error: TAR_BAD_ARCHIVE: Unrecognized archive format",     "reason": {         "errorType": "Error",         "errorMessage": "TAR_BAD_ARCHIVE: Unrecognized archive format",         "code": "TAR_BAD_ARCHIVE",         "recoverable": false,         "file": "/tmp/spectral_binary.tar.gz",         "cwd": "/tmp/spectral",         "tarCode": "TAR_BAD_ARCHIVE",         "stack": [             "Error: TAR_BAD_ARCHIVE: Unrecognized archive format",             "    at UnpackSync.warn (/var/task/webpack:/Users/chengazit/git/spectral-hub/packages/spectral-gitlab-webhook-scanner/node_modules/spectral-hub-shared/node_modules/tar/lib/warn-mixin.js:19:1)",             "    at UnpackSync.warn (/var/task/webpack:/Users/chengazit/git/spectral-hub/packages/spectral-gitlab-webhook-scanner/node_modules/spectral-hub-shared/node_modules/tar/lib/unpack.js:220:1)",             "    at UnpackSync.<anonymous> (/var/task/webpack:/Users/chengazit/git/spectral-hub/packages/spectral-gitlab-webhook-scanner/node_modules/spectral-hub-shared/node_modules/tar/lib/parse.js:81:1)",             "    at UnpackSync.emit (events.js:412:35)",             "    at UnpackSync.[emit] (/var/task/webpack:/Users/chengazit/git/spectral-hub/packages/spectral-gitlab-webhook-scanner/node_modules/spectral-hub-shared/node_modules/tar/lib/parse.js:285:1)",             "    at UnpackSync.[maybeEnd] (/var/task/webpack:/Users/chengazit/git/spectral-hub/packages/spectral-gitlab-webhook-scanner/node_modules/spectral-hub-shared/node_modules/tar/lib/parse.js:401:1)",             "    at UnpackSync.[consumeChunk] (/var/task/webpack:/Users/chengazit/git/spectral-hub/packages/spectral-gitlab-webhook-scanner/node_modules/spectral-hub-shared/node_modules/tar/lib/parse.js:432:1)",             "    at UnpackSync.write (/var/task/webpack:/Users/chengazit/git/spectral-hub/packages/spectral-gitlab-webhook-scanner/node_modules/spectral-hub-shared/node_modules/tar/lib/parse.js:364:1)",             "    at UnpackSync.end (/var/task/webpack:/Users/chengazit/git/spectral-hub/packages/spectral-gitlab-webhook-scanner/node_modules/spectral-hub-shared/node_modules/tar/lib/parse.js:477:1)",             "    at Pipe.end (/var/task/webpack:/Users/chengazit/git/spectral-hub/packages/spectral-gitlab-webhook-scanner/node_modules/spectral-hub-shared/node_modules/minipass/index.js:75:1)"         ]     },     "promise": {},     "stack": [         "Runtime.UnhandledPromiseRejection: Error: TAR_BAD_ARCHIVE: Unrecognized archive format",         "    at process.<anonymous> (/var/runtime/index.js:35:15)",         "    at process.emit (events.js:400:28)",         "    at process.emit (/var/task/webpack:/Users/chengazit/git/spectral-hub/packages/spectral-gitlab-webhook-scanner/node_modules/source-map-support/source-map-support.js:516:1)",         "    at processPromiseRejections (internal/process/promises.js:245:33)",         "    at processTicksAndRejections (internal/process/task_queues.js:96:32)"     ] }
Unknown application error occurredRuntime.Unknown
END RequestId: b4d8760e-6997-4f55-947a-72eca668528d
REPORT RequestId: b4d8760e-6997-4f55-947a-72eca668528d	Duration: 1043.08 ms	Billed Duration: 1044 ms	Memory Size: 1024 MB	Max Memory Used: 92 MB
```

**Comment by zamirTo1** [comment]
@ChengaDev don't know if that is related, but it seems that the binary file the lambda is trying to download is located on your computer.
`/var/task/webpack:/Users/chengazit/git/spectral-hub/packages/`

**Comment by ChengaDev** [comment]
@zamirTo1 The scanner is being downloaded from an external link based on your Spectral DSN.
Can you make sure you have entered a valid DSN (with a valid host) as SPECTRAL_DSN env var?

Regarding the local path, it seems webpack is keeping it for some reason but this path is not being used during the execution. I'll make sure it won't be shown.

**Comment by zamirTo1** [comment]
@ChengaDev it was the SPECTRAL_DSN, thank you!
